/**:
  ros__parameters:
    sc_db_path: "/mnt/nvme/workspace/fast_lio_ws/maps/fastlio/sc_database.txt"
    scan_topic: "/cloud_registered_body_1"
    initialpose_topic: "/initialpose"
    confidence_topic: "/localization_3d_confidence"
    match_threshold: 0.45
    confidence_threshold: 0.55
    publish_cooldown_sec: 15.0
    require_low_confidence: true
    num_sectors: 60
    apply_leveling_rotation: true
    leveling_quaternion: [-0.00394028, 0.24367785, 0.00970223, 0.96979969]
